// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCgpH-O2Pgv24R18zIpo11AvYl0Tixxs',
    appId: '1:677024216343:web:71fcb961ff10f22bcf7352',
    messagingSenderId: '677024216343',
    projectId: 'loginform-86144',
    authDomain: 'loginform-86144.firebaseapp.com',
    storageBucket: 'loginform-86144.appspot.com',
    measurementId: 'G-VJ9TERQLBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZoPbikY5uNYT_F01zO3hU-_xY7Dv7KI',
    appId: '1:677024216343:android:dce001cafab7545bcf7352',
    messagingSenderId: '677024216343',
    projectId: 'loginform-86144',
    storageBucket: 'loginform-86144.appspot.com',
  );
}
